# Generated by Django 5.2.9 on 2025-12-14 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('source', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('usda', 'USDA'), ('openfoodfacts', 'Open Food Facts')], default='user', max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('currency', models.CharField(default='EGP', max_length=10)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_prices', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='foods.food')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.FloatField()),
                ('protein', models.FloatField()),
                ('protein_type', models.CharField(choices=[('vegan', 'Vegan'), ('dairy', 'Dairy'), ('meat', 'Meat'), ('other', 'Other')], default='other', max_length=50)),
                ('carbohydrates', models.FloatField()),
                ('fats', models.FloatField()),
                ('fiber', models.FloatField(blank=True, null=True)),
                ('sugar', models.FloatField(blank=True, null=True)),
                ('sodium', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('calcium', models.FloatField(blank=True, null=True)),
                ('potassium', models.FloatField(blank=True, null=True)),
                ('vitamins', models.JSONField(blank=True, null=True)),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='foods.food')),
            ],
        ),
        migrations.CreateModel(
            name='ServingSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serving_sizes', to='foods.food')),
            ],
        ),
    ]
