# Generated by Django 5.2.9 on 2025-12-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_recipe_is_public_alter_servingsize_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='off_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
