# Generated by Django 5.2.9 on 2025-12-28 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_fooditem_off_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='price_quantity',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='price_unit',
            field=models.CharField(choices=[('g', 'Gram'), ('ml', 'Milliliter'), ('serving', 'Serving'), ('piece', 'Piece')], default='g', max_length=10),
        ),
        migrations.AddField(
            model_name='nutritionprofile',
            name='nutrition_basis',
            field=models.CharField(default='per_100g', max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
