# Generated by Django 5.2.9 on 2026-01-07 07:40

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Recipe = apps.get_model("foods", "Recipe")
    for recipe in Recipe.objects.all():
        base_slug = slugify(recipe.name) or "recipe"
        slug = base_slug
        counter = 1
        while Recipe.objects.filter(slug=slug).exclude(pk=recipe.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        recipe.slug = slug
        recipe.save()


class Migration(migrations.Migration):

    dependencies = [
        ("foods", "0004_fooditem_price_quantity_fooditem_price_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
