# Generated by Django 5.2.9 on 2026-01-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0008_fooditem_user_alter_fooditem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
