# Generated by Django 5.2.9 on 2026-01-15 00:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0010_alter_meal_name_alter_meal_slug_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='meal',
            unique_together={('user', 'slug', 'name', 'meal_type')},
        ),
    ]
