# Generated by Django 5.2.9 on 2026-01-03 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='is_coach',
            field=models.BooleanField(default=False),
        ),
    ]
