# Generated by Django 5.2.9 on 2026-01-13 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('SUPPLEMENT', 'Supplement'), ('HERB', 'Herb'), ('MEAL', 'Meal'), ('SNACK', 'Snack')], max_length=20),
        ),
    ]
