# Generated by Django 5.2.9 on 2025-12-22 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userhealthdata',
            old_name='targer_macros',
            new_name='target_macros',
        ),
    ]
