# Generated by Django 5.2.9 on 2026-01-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='contact_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
