# Generated by Django 5.2.9 on 2026-01-15 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coaching', '0002_coachprofile_contact_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCoachRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Coach Request',
                'verbose_name_plural': 'Pending Coach Requests',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coaching.coachrequest',),
        ),
    ]
